// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UserEvents
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C2S_Logout : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static C2S_Logout GetRootAsC2S_Logout(ByteBuffer _bb) { return GetRootAsC2S_Logout(_bb, new C2S_Logout()); }
  public static C2S_Logout GetRootAsC2S_Logout(ByteBuffer _bb, C2S_Logout obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_Logout __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<UserEvents.C2S_Logout> CreateC2S_Logout(FlatBufferBuilder builder,
      uint player_id = 0) {
    builder.StartTable(1);
    C2S_Logout.AddPlayerId(builder, player_id);
    return C2S_Logout.EndC2S_Logout(builder);
  }

  public static void StartC2S_Logout(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayerId(FlatBufferBuilder builder, uint playerId) { builder.AddUint(0, playerId, 0); }
  public static Offset<UserEvents.C2S_Logout> EndC2S_Logout(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UserEvents.C2S_Logout>(o);
  }
}


static public class C2S_LogoutVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayerId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
