// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UserEvents
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C2S_PlayerMoveData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static C2S_PlayerMoveData GetRootAsC2S_PlayerMoveData(ByteBuffer _bb) { return GetRootAsC2S_PlayerMoveData(_bb, new C2S_PlayerMoveData()); }
  public static C2S_PlayerMoveData GetRootAsC2S_PlayerMoveData(ByteBuffer _bb, C2S_PlayerMoveData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_PlayerMoveData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ushort PositionX { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort PositionY { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte KeyCode { get { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<UserEvents.C2S_PlayerMoveData> CreateC2S_PlayerMoveData(FlatBufferBuilder builder,
      uint player_id = 0,
      ushort position_x = 0,
      ushort position_y = 0,
      byte key_code = 0) {
    builder.StartTable(4);
    C2S_PlayerMoveData.AddPlayerId(builder, player_id);
    C2S_PlayerMoveData.AddPositionY(builder, position_y);
    C2S_PlayerMoveData.AddPositionX(builder, position_x);
    C2S_PlayerMoveData.AddKeyCode(builder, key_code);
    return C2S_PlayerMoveData.EndC2S_PlayerMoveData(builder);
  }

  public static void StartC2S_PlayerMoveData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddPlayerId(FlatBufferBuilder builder, uint playerId) { builder.AddUint(0, playerId, 0); }
  public static void AddPositionX(FlatBufferBuilder builder, ushort positionX) { builder.AddUshort(1, positionX, 0); }
  public static void AddPositionY(FlatBufferBuilder builder, ushort positionY) { builder.AddUshort(2, positionY, 0); }
  public static void AddKeyCode(FlatBufferBuilder builder, byte keyCode) { builder.AddByte(3, keyCode, 0); }
  public static Offset<UserEvents.C2S_PlayerMoveData> EndC2S_PlayerMoveData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UserEvents.C2S_PlayerMoveData>(o);
  }
}


static public class C2S_PlayerMoveDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayerId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PositionX*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 8 /*PositionY*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*KeyCode*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
