// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UserEvents
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C2S_Login : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static C2S_Login GetRootAsC2S_Login(ByteBuffer _bb) { return GetRootAsC2S_Login(_bb, new C2S_Login()); }
  public static C2S_Login GetRootAsC2S_Login(ByteBuffer _bb, C2S_Login obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_Login __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Userid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUseridBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUseridBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUseridArray() { return __p.__vector_as_array<byte>(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPasswordBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPasswordArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<UserEvents.C2S_Login> CreateC2S_Login(FlatBufferBuilder builder,
      StringOffset useridOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartTable(2);
    C2S_Login.AddPassword(builder, passwordOffset);
    C2S_Login.AddUserid(builder, useridOffset);
    return C2S_Login.EndC2S_Login(builder);
  }

  public static void StartC2S_Login(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUserid(FlatBufferBuilder builder, StringOffset useridOffset) { builder.AddOffset(0, useridOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static Offset<UserEvents.C2S_Login> EndC2S_Login(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UserEvents.C2S_Login>(o);
  }
}


static public class C2S_LoginVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Userid*/, false)
      && verifier.VerifyString(tablePos, 6 /*Password*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
