// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UserEvents
{

public enum EventType : byte
{
  NONE = 0,
  C2S_Login = 1,
  S2C_Login = 2,
  C2S_PlayerMoveData = 3,
  S2C_PlayerMoveData = 4,
  C2S_Logout = 5,
  S2C_Logout = 6,
};



static public class EventTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((EventType)typeId)
    {
      case EventType.C2S_Login:
        result = UserEvents.C2S_LoginVerify.Verify(verifier, tablePos);
        break;
      case EventType.S2C_Login:
        result = UserEvents.S2C_LoginVerify.Verify(verifier, tablePos);
        break;
      case EventType.C2S_PlayerMoveData:
        result = UserEvents.C2S_PlayerMoveDataVerify.Verify(verifier, tablePos);
        break;
      case EventType.S2C_PlayerMoveData:
        result = UserEvents.S2C_PlayerMoveDataVerify.Verify(verifier, tablePos);
        break;
      case EventType.C2S_Logout:
        result = UserEvents.C2S_LogoutVerify.Verify(verifier, tablePos);
        break;
      case EventType.S2C_Logout:
        result = UserEvents.S2C_LogoutVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
