// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UserEvents
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S2C_Login : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static S2C_Login GetRootAsS2C_Login(ByteBuffer _bb) { return GetRootAsS2C_Login(_bb, new S2C_Login()); }
  public static S2C_Login GetRootAsS2C_Login(ByteBuffer _bb, S2C_Login obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_Login __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(6); }
  public ushort PositionX { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort PositionY { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public UserEvents.Color? Color { get { int o = __p.__offset(12); return o != 0 ? (UserEvents.Color?)(new UserEvents.Color()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartS2C_Login(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(1, messageOffset.Value, 0); }
  public static void AddPositionX(FlatBufferBuilder builder, ushort positionX) { builder.AddUshort(2, positionX, 0); }
  public static void AddPositionY(FlatBufferBuilder builder, ushort positionY) { builder.AddUshort(3, positionY, 0); }
  public static void AddColor(FlatBufferBuilder builder, Offset<UserEvents.Color> colorOffset) { builder.AddStruct(4, colorOffset.Value, 0); }
  public static Offset<UserEvents.S2C_Login> EndS2C_Login(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UserEvents.S2C_Login>(o);
  }
}


static public class S2C_LoginVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Success*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 6 /*Message*/, false)
      && verifier.VerifyField(tablePos, 8 /*PositionX*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*PositionY*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 12 /*Color*/, 3 /*UserEvents.Color*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
