// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UserEvents
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S2C_Logout : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static S2C_Logout GetRootAsS2C_Logout(ByteBuffer _bb) { return GetRootAsS2C_Logout(_bb, new S2C_Logout()); }
  public static S2C_Logout GetRootAsS2C_Logout(ByteBuffer _bb, S2C_Logout obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_Logout __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool Success { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Message { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<UserEvents.S2C_Logout> CreateS2C_Logout(FlatBufferBuilder builder,
      uint player_id = 0,
      bool success = false,
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(3);
    S2C_Logout.AddMessage(builder, messageOffset);
    S2C_Logout.AddPlayerId(builder, player_id);
    S2C_Logout.AddSuccess(builder, success);
    return S2C_Logout.EndS2C_Logout(builder);
  }

  public static void StartS2C_Logout(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPlayerId(FlatBufferBuilder builder, uint playerId) { builder.AddUint(0, playerId, 0); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(1, success, false); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(2, messageOffset.Value, 0); }
  public static Offset<UserEvents.S2C_Logout> EndS2C_Logout(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UserEvents.S2C_Logout>(o);
  }
}


static public class S2C_LogoutVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayerId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Success*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 8 /*Message*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
