// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UserEvents
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S2C_PlayerMoveData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static S2C_PlayerMoveData GetRootAsS2C_PlayerMoveData(ByteBuffer _bb) { return GetRootAsS2C_PlayerMoveData(_bb, new S2C_PlayerMoveData()); }
  public static S2C_PlayerMoveData GetRootAsS2C_PlayerMoveData(ByteBuffer _bb, S2C_PlayerMoveData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_PlayerMoveData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ushort PositionX { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort PositionY { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<UserEvents.S2C_PlayerMoveData> CreateS2C_PlayerMoveData(FlatBufferBuilder builder,
      uint player_id = 0,
      ushort position_x = 0,
      ushort position_y = 0) {
    builder.StartTable(3);
    S2C_PlayerMoveData.AddPlayerId(builder, player_id);
    S2C_PlayerMoveData.AddPositionY(builder, position_y);
    S2C_PlayerMoveData.AddPositionX(builder, position_x);
    return S2C_PlayerMoveData.EndS2C_PlayerMoveData(builder);
  }

  public static void StartS2C_PlayerMoveData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPlayerId(FlatBufferBuilder builder, uint playerId) { builder.AddUint(0, playerId, 0); }
  public static void AddPositionX(FlatBufferBuilder builder, ushort positionX) { builder.AddUshort(1, positionX, 0); }
  public static void AddPositionY(FlatBufferBuilder builder, ushort positionY) { builder.AddUshort(2, positionY, 0); }
  public static Offset<UserEvents.S2C_PlayerMoveData> EndS2C_PlayerMoveData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UserEvents.S2C_PlayerMoveData>(o);
  }
}


static public class S2C_PlayerMoveDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayerId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PositionX*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 8 /*PositionY*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
